[package]
name = "tracing-grpc"
version = "0.1.0"
edition = "2021"
publish = false

[[bin]] # Bin to run the gRPC server
name = "grpc-server"
path = "src/server.rs"

[[bin]] # Bin to run the gRPC client
name = "grpc-client"
path = "src/client.rs"

[dependencies]
http = "0.2"
tonic = "0.8.2"
prost = "0.11"
tokio = { version = "1.0", features = ["full"] }
opentelemetry = { version = "0.18", features = ["rt-tokio"] }
opentelemetry-jaeger = "0.17"
tracing = "0.1"
tracing-subscriber = "0.3"
tracing-opentelemetry = "0.18"
tracing-futures = "0.2"

[build-dependencies]
tonic-build = "0.8.2"
